### ISSUE TITLE
A general question...

### ISSUE THREAD

**Issue by thanaclara** [jackoalan/swrs_musyx#1]
I was pointed in this direction by another user in order to work with some music files for rogue squadron 3D. I'm getting errors when trying to generate in CMake. Is there any specific procedure for generating these files correctly?

**Comment by jackoalan** [comment]
Ah, yes.. I've yet to write a bootstrap script for standalone (vs. library builds)

Which OS are you running and what compiler do you plan on using? I'll ensure your platform will work for standalone building after you run that script.

**Comment by jackoalan** [comment]
Also, are you trying to get MIDI data? This program will only give you raw samples at their base pitch

**Comment by thanaclara** [comment]
Well I was playing around with compiling it within Visual studio but I'm pretty new at this. Yes I am trying to get the MIDI data extracted from the game. I was aware that this may not have that sort of functionality but I still wanted to play around with it just to see if it could lend me any insight on that sort of thing. I know it uses SNG files but none of the SNG software that I have acquired seems to be compatible with these specific SNG files for some reason.

**Comment by jackoalan** [comment]
Yea, MusyX 1 (MoSys as it was originally called) songs are rather crazy in their contents. Rogue Squadron was the first game to use it by the looks of it. Factor5 was able to get away with this crazy representation since audio on the N64 (and PC) is essentially CPU-bound, directly competing with the game for CPU time, but flexible enough to play just about any sort of command. 

MusyX 2 was put together during the original development of the Dolphin SDK, and became a very popular audio system among GameCube devs; further evolving to MusyX 3 later in the GameCube's life. In order to play nice with the GameCube's fancy new DSP chip, the song representation and voice handling was simplified tremendously.

I've written a player for MusyX 2 songs, which are much easier to play out using the MusyX SoundMacros directly. I'm not really up to reverse engineering the crazy original SNG format though. 
https://github.com/AxioDL/amuse

RS2's songs use this newer format, and I'm interested in tracking down other GameCube games that have such songs. A SNGv2-to-MIDI converter tool (and vice-versa) is in the works. 

You might just want to use the pre-built Windows binary if you're just interested in the raw samples:
https://github.com/jackoalan/swrs_musyx/releases

To compile, you'll need to install our Athena framework, which enables us to make data-extracting programs like `swrs_musyx` with small amounts of code:
https://github.com/libAthena/athena/releases

That should take care of the `atdna` package errors

**Comment by jackoalan** [comment]
Hello!

Just an update on this matter: Thanks to SubDrag (author of N64 Sound Tool), I now have a much clearer picture of how the N64 SNG format works.. I already have recognizable melodies from the data, just need to make sure it's correctly assembled into the full song.

I'll keep you posted, but the SNG functionality will be added to a different repository: https://github.com/AxioDL/amuse

**Comment by thanaclara** [comment]
That is fantastic!! I really appreciate you being willing to go out of your way for this and providing me the information about the different variations of Musyx and how to compile everything. It's going to help out big time. Has the ability to play the SNG's been added in this iteration or is that TBA?

**Comment by jackoalan** [comment]
That is actually a work-in-progress..

It can directly playback SNGs from (N64, PC, GCN) implementations so far via `amuseplay`. Conversion to/from MIDI is being worked-on here:
https://github.com/AxioDL/amuse/blob/master/lib/SongConverter.cpp

There will be a command-line tool called `amuseconv` that can convert between SNG and MIDI, as well as ripping entire games' audio data in-bulk (including songs).

Eventually, `amuseconv` will support every aspect of MusyX's data model, including samples as .wav files, and SoundMacros as editable text files.

**Comment by thanaclara** [comment]
I see, I had trouble trying to figure out how to play the SNG's in amuseplay but I was able to control the sequencer with the keyboard. However the MIDI converter is definitely what I am looking forward to and will be checking back for updates quite eagerly :D

**Comment by jackoalan** [comment]
Yea, just pushed a large commit of code for it.. Still not quite ready, I'll try to get fully debugged tomorrow.

Closing this issue in the meantime

**Comment by jackoalan** [comment]
Hello again!

The first Windows build of `amuseconv` is ready for testing here:
https://github.com/AxioDL/amuse/releases

Please let me know if you experience problems with the converted data

**Comment by thanaclara** [comment]
Well I seemed to have gotten a bunch of garbled MIDI tracks that were 25 hours long when I used it on the PC file but it seems to have worked perfectly as far as I can tell when I used it on the ROM file. Thanks a million!

**Comment by jackoalan** [comment]
Ah lol, of course the one platform i didn't test much.. Thanks for the heads up about the PC data, I'll have to make sure i'm working with the intel-optimized data correctly
